# Assembly

## Outline

üí°‚ÑπÔ∏è You can find an outline (table of contents) in the upper right corner of this GitHub file and expand it by clicking on the icon. Click on the titles to jump to the corresponding section.

![](images/Assembly/outline.png)

## Part list

Please check the part list in the [BOM section](Shopping_list.md)

## Tool list

Check that you have all the tools you need:

- A set of screw drivers and wrenches for hexagon screws (M3, M5 and M8)
- A set of allen keys
- Pliers

## Assembly

The assembly instructions are divided into several modules. These do not necessarily have to be assembled in the order listed below. Several people can also work on different modules at the same time. At the end, all modules must be assembled together.

## 1. Frame

<table> <tr> <td> <img width="300" src="images/Assembly/001-A.png"> </td> <td> <ul>
        <li>Insert 2 t-nuts (M5) in one of the t-slot profiles (length 41 mm). You will need them later to assemble the brake.</li>
</table>

<table> <tr> <td> <img width="1500" src="images/Assembly/001b.png"> <br> <img width="1500" src="images/Assembly/004b.png"> <br> <img width="1500" src="images/Assembly/005.png"></td> <td> <ul>
        <li>Assamble the following 20x20 t-slot profiles:
          <ul>
            <li>length 509 mm (2 pieces)</li>
            <li>length 41 mm (2 pieces)</li>
          </ul>
        </li>
        <li>Use four 20x20 angles for mounting</li>
        <li>For each angle, you will need 2x M5 screws and 2x t-nuts</li>
        <li>Make sure to move the 41-mm-profiles to the right position (80 mm for the back part, 71 mm for the front part)</li>
        <li>Make sure to put the part with the 2 t-nuts (for the brake) in the back part of the frame (with a distance 80 mm)</li>
        <li>Make sure that the drilled holes are in the back</li>
        <li>Make sure that everything is parallel and at right angles</li>
        <li>Insert the M8 x 95 screw through the holes and make sure that it fits well</li>
        <li>Do not fasten the screw yet. If the screw fits, remove it again. The rear wheel will be mounted later.</li>
      </ul> </td> </tr> </table>

<table> <tr> <td> <img width="500" src="images/Assembly/006b.png"> <br> <img width="250" src="images/Assembly/007.png"> <br> <img width="250" src="images/Assembly/008.png"> </td> <td> <ul>
        <li>Insert 4x t-nuts (with M5 holes) in the frame (2 on each side)</li>
        <li>Insert them on the front part of the frame (where the distance of the profile is 71 mm and where are no holes)</li>
        <li>Mount the two angles using 2x M5 x 10 countersunk screws for each part</li>
        <li>Ensure that the angles are flush with the profiles</li>
        <li>Insert the M8 x 65 screw through the bigger hole and the bolt through the smaller hole and make sure everything fits well</li>
</table>

<table> <tr> <td> <img width="500" src="images/Assembly/009.png"> <br> <img width="500" src="images/Assembly/010.png"> <br> <img width="500" src="images/Assembly/011.png"> <br> <img width="500" src="images/Assembly/012.png"></td> <td> <ul>
        <li>Insert the 3D-printed (nylon) plain bearing in the largest hole of the cross connection. It should sit tightly inside the hole.</li>
        <li>Mount the cross connection between the angles, using two 3D-printed spacers (18 x 2,5 or 18 x 1,9) and a M8 x 65 screw with washers on each side (washers not shown in the image)</li>
        <li>Try the 18 x 2,5 spacers first. If they don't fit, try the 18 x 1,9 ones. If none of them fit, edit the file in FreeCAD or in a slicer software and print spacers that fit well. The cross connection part should not wobble</li>
        <li>Tighten the screw with a M8 nut (not shown in the image)</li>
        <li>Test the connection. The part should be rotatable.</li>
</table>

<table> <tr> <td> <img width="2000" src="images/Assembly/013.png"> </td> <td> <ul>
        <li>The frame is now fully assembled. Set it aside and continue with the assembly of the other modules.</li>
</table>

## 2. Front wheel and fork

<table> <tr> <td> <img width="400" src="images/Assembly/014.png"> <br> <img width="200" src="images/Assembly/015.png"> <br> <img width="400" src="images/Assembly/016b.png"> </td> <td> <ul>
        <li>Prepare the following parts
                <ul>
                        <li>Fork</li>
                        <li>Front wheel (diameter 120 mm)</li>
                        <li>2x 3D-printed spacers (11 x 5 mm)</li>
                        <li>M8 x 50 screw</li>
                        <li>M8 nut (only shown in the third image)</li>
                        <li>2x washers (not shown in the images)</li>
                </ul>
        </li>
        <li>Have a pair of pliers ready that are narrow enough to insert the spacers.</li>
        <li>Put a washer on the screw</li>
        <li>Insert the screw through the hole (just a few millimeters beyond the hole)</li>
        <li>Put one of the spacers on the tip of the screw</li>
        <li>Hold the wheel and the other spacer (using the pliers) in position, then push the screw all the way through</li>
        <li>Put the second washer on the end of the screw and fasten it with a M8 nut</li>
        <li>Test the assembly. Make sure the wheel spins well and that it doesn't wobble.</li>
</table>

## 3. Handlebar (top part)

<table> <tr> <td>
        <img width="100" src="images/Assembly/018.png"> <br> 
        <img width="200" src="images/Assembly/019.png"> <br> 
        <img width="200" src="images/Assembly/020b.png"> <br> 
        <img width="200" src="images/Assembly/021.png">
</td> <td> <ul>
        <li>Assemble the two 30x30 profiles together (lenght 364 and 112 mm)</li>
        <li>Use two 30x30 angles for mounting</li>
        <li>For each angle, you will need 2x M5 screws and 2x t-nuts</li>
        <li>Make sure that the short profile on the top is centered</li>
        <li>If available, insert a cover cap on each angle (not shown in the images, not necessary, only for appearance)</li>
        <li>Insert two t-nuts (M3) in the front part of the long profile (red circles ‚≠ï in the image)</li>
        <li>Mount the 3D-printed case, using two M3 x 12 countersunk screws (screw them into the t-nuts)</li>
</table>

<table> <tr> <td>
        <img width="400" src="images/Assembly/022.png"> <br> 
        <img width="400" src="images/Assembly/023.png">
</td> <td> <ul>
        <li>The distance between the top edge of the 3D-printed case and the edge of the angle should be about 14 mm </li>
        <li>This is important, so the front cover will fit. You can correct the distance later when mounting the front cover.</li>
        <li>Ensure that the countersunk screws are well hidden below the surface of the cover <br> so that they do not scratch the inner wall of the aluminum square profile later on.</li>
</table>
